# Generated by Django 4.2.2 on 2023-06-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id_host', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('adresse_ip', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=240)),
                ('id_equipement', models.CharField(max_length=240)),
                ('id_service', models.CharField(max_length=70)),
                ('id_type', models.IntegerField()),
            ],
        ),
    ]
