# Generated by Django 4.2.5 on 2023-10-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('libelle_equipement', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHost',
            fields=[
                ('id_group_host', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('libelle_group_host', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryConnect',
            fields=[
                ('id_hist', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=40)),
                ('last_connect', models.DateTimeField()),
                ('ip_connect', models.CharField(max_length=20)),
                ('lib_connect', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id_privilege', models.AutoField(primary_key=True, serialize=False)),
                ('lib_privilege', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('libelle_service', models.CharField(max_length=255)),
                ('email_service', models.CharField(max_length=255)),
                ('dept_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id_systeme', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle_systeme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=60)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('last_connect', models.DateField()),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateField()),
                ('id_privilege', models.CharField(max_length=20)),
            ],
        ),
    ]
