# Generated by Django 4.2.5 on 2023-10-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup', '0002_equipement_grouphost_historyconnect_privilege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='adresse_ip',
            field=models.CharField(max_length=20),
        ),
    ]
